---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: ITG
  vars:
    day: "{{ ansible_date_time.day }}"
    month: "{{ansible_date_time.month}}"
    year: "{{ansible_date_time.year}}"
    backup_directory: "./backup/{{year}}/{{month}}_{{day}}/"
    backup_filename: "{{inventory_hostname}}.config"
    fullpath: "{{backup_directory}}/{{backup_filename}}"

  tasks:
    - name: ENSURE THAT THE DESTINATION PATH EXISTS
      file:
        path: "{{backup_directory}}"
        state: directory

    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "{{fullpath}}"

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        line: "Building configuration..."
        state: absent

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "{{fullpath}}"
        regexp: 'Current configuration.*'
        state: absent
