- name: "GENERATE VERSION REPORT"
  hosts: all
  gather_facts: false

  roles:
    - ansible-network.network-engine

  tasks:
    - name: CAPTURE SHOW VERSION
      ios_command:
        commands:
          - show version
      register: output

    - name: PARSE THE RAW OUTPUT
      command_parser:
        file: "parsers/show_version.yaml"
        content: "{{ output.stdout[0] }}"

    - name: DISPLAY THE PARSED DATA
      debug:
        var: version_facts