---
- name: "CONFIGURE CISCO SWITCHES WITH SECURITY FEATURES"
  hosts: all
  gather_facts: false

  tasks:

    - name: "REMOVE EXISTING BANNERS"
      ios_banner:
        banner: "{{ item }}"
        state: absent
      loop:
        - motd
        - exec

    - name: "UPDATE MOTD BANNER"
      ios_banner:
        banner: motd
        text: |
          ********************************************************
          *  WARNING :
          *        UNAUTHORIZED ACCESS IS
          *              STRICTLY PROHIBITED.
          *                        |        |
          *                       |||      |||
          *                    .:|||||:..:|||||:.
          *                    Cisco Sytems, Inc.
          *
          * BE CAREFUL ! THIS DEVICE IS OWNED BY $ENTREPRISE.
        
          ********************************************************
        state: present

    - name: "UPDATE LOGIN BANNER"
      ios_banner:
        banner: login
        text: |
          ----------------------------------------
          |
          | This banner was generated by Ansible 
          |
          ----------------------------------------
          |
          | You are logged into $(hostname)
          |
          | Your TTY LINE IS = $(line).
          | 
          ----------------------------------------
        state: present
        
