# This documentation is a code write in <yaml> named playbook. It is useful for cisco devices configurations. 
# Here is an example of cisco switches configurations using Ansible
#                                   ENJOY !!!!!!!
###                            AL BARZAKOUL MAKHTOUM                                       ###

---
- name: "CONFIGURE CISCO SWITCHES WITH SECURITY FEATURES"
  hosts: all
  gather_facts: false

  tasks:

    - name: "REMOVE EXISTING BANNERS"
      ios_banner:
        banner: "{{ item }}"
        state: absent
      loop:
        - motd
        - exec

    - name: "UPDATE MOTD BANNER"
      ios_banner:
        banner: motd
        text: |
          ********************************************************
          *  WARNING :
          *        UNAUTHORIZED ACCESS IS
          *              STRICTLY PROHIBITED.
          *                        |        |
          *                       |||      |||
          *                    .:|||||:..:|||||:.
          *                    Cisco Sytems, Inc.
          *
          * BE CAREFUL ! THIS DEVICE IS OWNED BY $ENTREPRISE.
        
          ********************************************************
        state: present

    - name: "UPDATE LOGIN BANNER"
      ios_banner:
        banner: login
        text: |
          ----------------------------------------
          |
          | This banner was generated by Ansible 
          |
          ----------------------------------------
          |
          | You are logged into $(hostname)
          |
          | Your TTY LINE IS = $(line).
          | 
          ----------------------------------------
        state: present

    - name: "CREATE USER READ WRITE"
      no_log: true
      ios_user:
        name: [Your_Super_User]
        privilege: 15
        hashed_password:
          type: 9
          value: $9[Your_Type9_Encrypt_Password]
        state: present
      tags: rw_user

    - name: "CREATE USER READ ONLY"
      no_log: true
      ios_user:
        name: [Your_ReadOnly_User]
        privilege: 7
        hashed_password:
          type: 9
          value: $9[Your_Type9_Encrypt_Password]
        state: present
      tags: ro_user

    - name: "CONFIGURE ENHANCED SWITCHES LOGGING MESSAGES"
      ios_config:
        commands:
           - service timestamps debug datetime msec localtime show-timezone
           - service timestamps log datetime msec localtime show-timezone
           - service sequence-numbers
           - logging buffered 81920 debugging
           - logging trap debugging
        match: exact
      tags: sw-log

    - name: "CONFIGURE SWITCH SECURITY BEST PRACTICES IN GLOBAL MODE"
      ios_config: 
        commands:
          - service password-encryption
          - no service password-recovery
          - no ip domain-lookup
          - no service pad
          - no ip http server
          - no ip http secure-server 
          - mac address-table aging-time 14400
          - mac address-table notification change
          - mac address-table notification mac-move
          - mls qos
          - udld aggressive
          - vlan dot1q tag native
        match: exact
      tags: hardening

    - name: "CONFIGURE SSH OPTION"
      ios_config:
        commands:
          - ip domain-name name.dom
          - crypto key generate rsa general-keys modulus 2048
          - ip ssh version 2
          - ip ssh logging events
          - ip ssh time-out 60
          - ip ssh authentication-retries 3
        match: exact
      tags: ssh

    - name: "CONFIGURE LINE VTY"
      ios_config:
        commands:
          - transport input ssh
          - logging synchronous
          - transport preferred ssh
          - transport output ssh
        parents: line vty 0 15
        match: exact
      tags: line-cf

    - name: "CONFIGURE LINE CONSOLE"
      ios_config:
        commands:
          - exec-timeout 0 0
          - password <your-password>
          - login authentication CONSOLE
          - transport output ssh
        parents: line console 0
        match: exact
      tags: line-cf

    - name: "CONFIGURE NTP AND NETWORK CLOCK"
      ios_config:
        commands:
          - clock timezone GMT+1 1 0
          - clock summer-time GMT+1 recurring last Sun Mar 2:00 last Sun Oct 3:00
          - ntp clock-period 36028925
          - ntp server <ip-add>
        match: exact
      tags: ntp

    - name: "CREATE VLANS"
      ios_config:
        commands:
          - name {{ item.name }}
        parents: vlan {{ item.number }}
      with_items:
        - { name: 'DESCRIPTION', number: 00 }
        - { name: 'DESCIPRION', number: 00}
      tags: vlan

    - name: "CONFIGURE INTERFACE VLAN"
      ios_config:
        commands:
          - description MANAGEMENT
          - ip address  <ip-add> <netmask>
        parents: interface VLANID
        after: ip default-gateway <ip-add>
      tags: ifvlan

    - name: "CONFIGURE SPANNING-TREE"
      ios_config: 
        commands:
          - spanning-tree mode rapid-pvst
          - spanning-tree logging
          - spanning-tree portfast bpduguard default
          - spanning-tree extend system-id
          - spanning-tree vlan 1-1024 priority 24576
        match: exact
      tags: stp

    - name: "CONFIGURE INTERFACE IN ACCESS MODE"
      ios_config:
        commands:
          - description {{ item.desc }}
          - switchport mode access
          - switchport access vlan {{ item.vlan_id }}
          - switchport port-security
          - switchport port-security maximum 3
          - switchport port-security mac-address sticky
          - switchport port-security violation shutdown
          - switchport port-security aging time 1
          - switchport port-security aging type inactivity
          - spanning-tree bpdufilter enable
          - spanning-tree bpduguard enable
          - spanning-tree portfast edge
          - storm-control broadcast level pps 500 250
          - storm-control multicast level pps 150 
          - storm-control action shutdown
          - ip dhcp snooping trust
        parents: interface {{ item.int_name }}
      with_items: 
        - { int_name: 'GigabitEthernetX/X', desc: 'DESCRIPTION', vlan_id: 00 }
        - { int_name: 'range GigabitEthernetX/X-Y', desc: 'DESCRIPTION', vlan_id: 00 }
        - { int_name: 'range GigabitEthernetX/X,GigabitEthernetX/Y', desc: 'DESCRIPTION', vlan_id: 00 }
      tags: ifconfig-access


    - name: "CONFIGURE INTERFACE IN TRUNK MODE"
      ios_config:
        commands:
          - description {{ item.desc }}
          - switchport mode trunk
          - switchport trunk allowed vlan {{ item.vlans_id }}
          - switchport nonegotiate
          - switchport trunk native vlan {{ item.native }}
          - spanning-tree guard root
          - mls qos trust cos
          - storm-control broadcast level pps 500
          - storm-control multicast level pps 2k 1K
          - storm-control action shutdown
          - ip dhcp snooping trust
        parents: interface {{ item.int_name}}
      with_items: 
        - { int_name: 'GigabitEthernetX/X', desc: 'DESCRIPTION', vlans_id: '00,00,...', native: 00 }
        - { int_name: 'range GigabitEthernetX/X-Y', desc: 'DESCRIPTION', vlans_id: '00,00,...', native: 00 }
        - { int_name: 'range GigabitEthernetX/X,GigabitEthernetX/Y', desc: 'DESCRIPTION', vlans_id: '00,00,...', native: 00 }
      tags: ifconfig-trunk

    - name: "CONFIGURE ERRDISABLE"
      ios_config: 
        commands:
          - errdisable recovery cause udld
          - errdisable recovery cause bpduguard
          - errdisable recovery cause security-violation
          - errdisable recovery cause dtp-flap
          - errdisable recovery cause link-flap
          - errdisable recovery cause psecure-violation
          - errdisable recovery cause port-mode-failure
          - errdisable recovery cause dhcp-rate-limit
          - errdisable recovery cause mac-limit
          - errdisable recovery cause storm-control
          - errdisable recovery cause inline-power
          - errdisable recovery cause arp-inspection
          - errdisable recovery interval 600
        match: exact
      tags: err

    - name: "CONFIGURE UNUSED INTERFACES"
      ios_config:
        commands:
          - description {{ item.desc }}
          - switchport access vlan {{ item.vlan_id }}
          - shutdown
        parents: interface {{ item.int_name}}
      with_items: 
        - {int_name: 'range GigabitEthernet X/X-Y', desc: 'UNUSED_IF', vlan_id: 00 }
      tags: unused

    - name: "CONFIGURE PARSER VIEW"
      ios_config:
        commands:
          - secret 5 $(md5_password)
          - commands exec include all traceroute
          - commands exec include all ping
          - commands exec exclude show startup-config
          - commands exec include all show
        parents: parser view access-su
      tags: view

    - name: "CONFIGURE SNMP"
      ios_config: 
        commands:
          - snmp-server group <group-name> v3 auth
          - snmp-server community <com-name> RW
          - snmp-server community <com-name> RO
          - snmp-server host <ip-add> version 2c <name>
          - snmp-server host <ip-add> version 2c <name>
          - snmp-server enable traps snmp authentication linkdown linkup coldstart warmstart
          - snmp-server enable traps transceiver all
          - snmp-server enable traps tty
          - snmp-server enable traps cpu threshold
          - snmp-server enable traps power-ethernet police
          - snmp-server enable traps vtp
          - snmp-server enable traps vlancreate
          - snmp-server enable traps vlandelete
          - snmp-server enable traps flash insertion removal
          - snmp-server enable traps port-security
          - snmp-server enable traps envmon fan shutdown supply temperature status
          - snmp-server enable traps cef resource-failure peer-state-change peer-fib-state-change inconsistency
          - snmp-server enable traps config-copy
          - snmp-server enable traps config
          - snmp-server enable traps config-ctid
          - snmp-server enable traps bridge newroot topologychange
          - snmp-server enable traps stpx inconsistency root-inconsistency loop-inconsistency
          - snmp-server enable traps syslog
          - snmp-server enable traps mac-notification change move threshold
          - snmp-server enable traps vlan-membership
          - snmp-server enable traps errdisable
        match: exact
      tags: snmp

    - name: "SAVE CONFIGURATION"
      cli_command:
        command: write
