- name: "SWITCHES OR ROUTERS INVENTORY"
  hosts: all
  gather_facts: false

  tasks:
    - name: "GATHER FACTS"
      cisco.ios.ios_facts:
      when: ansible_network_os == 'cisco.ios.ios'

    - name: "RENDER FACTS AS A REPORT"
      template:
        src: templates-jinja2/os_report.j2
        dest: reports/{{ inventory_hostname }}.md

    - name: "CONSOLIDATE THE IOS DATA"
      assemble:
        src: reports/
        dest: os_report.md
      delegate_to: localhost
      run_once: yes
